# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-eligibility:
    build:
      target: development
    image: ffc-tcg-eligibility-development
    container_name: ffc-tcg-eligibility-development
    ports:
      - "3051:3051"
      - "9251:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
