services:
  ffc-tcg-eligibility:
    build:
      context: .
      target: production
    image: ffc-tcg-eligibility
    container_name: ffc-tcg-eligibility
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-eligibility-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      ELIGIBILITY_TOPIC_ADDRESS: ${ELIGIBILITY_TOPIC_ADDRESS:-ffc-tcg-eligibility-request}${MESSAGE_QUEUE_SUFFIX}
      ELIGIBILITY_SUBSCRIPTION_ADDRESS: ${ELIGIBILITY_SUBSCRIPTION_ADDRESS:-ffc-tcg-eligibility}${MESSAGE_QUEUE_SUFFIX}
      ELIGIBILITYRESPONSE_QUEUE_ADDRESS: ${ELIGIBILITYRESPONSE_QUEUE_ADDRESS:-ffc-tcg-eligibility-response}${MESSAGE_QUEUE_SUFFIX}
