services:
  ffc-tcg-eligibility:
    build:
      context: .
      target: production
    image: ffc-tcg-eligibility
    container_name: ffc-tcg-eligibility
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-eligibility-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
